version: '3'

services:
    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        tty: true
        restart: unless-stopped
        ports:
            - "8081:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: php
        environment:
            SERVICE_NAME: php
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "8082:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306

networks:
    laravel:
